### ISSUE TITLE
"control panel" interface to be able to run things w/o digging out laptop

### ISSUE THREAD

**Issue by mrgriscom** [mrgriscom/ellis-dome#12]
cheap tablet?

**Comment by shen-tian** [comment]
I've got that cheap windows tablet still. Are we talking about a web interface? [TouchOSC](https://itunes.apple.com/us/app/touchosc/id288120394?mt=8) seems to be used quite a lot for these things, but depends on usecase. Think Sam has an iPad 2 that we might be able to borrow.

**Comment by mrgriscom** [comment]
have a quite functional web-based UI now, so closing this
