### ISSUE TITLE
ability to quickly skip pixels

### ISSUE THREAD

**Issue by shen-tian** [mrgriscom/ellis-dome#5]
Scenario: one pixel breaks, for whatever reason. Fastest field fix would be to cut it out, and use crocodile clip wires to "skip" it. However, now everything is "out by one".

Suggested solution: have an easy way to specify which (logical) pixel has been skipped (some sort of config file?), so when placing them in OPC.java (or LayoutUitl.java?), it skips it as well. Not sure how this affects things `fcserver` side, but we can test it. We can then edit the config, restart, and everything is back to normal again, bar what appears to be a dead pixel.

Alternative: make a few strips of wire with a pixel in it. Use these as "patches". (i.e. fix it in hardware only).

Thoughts?

**Comment by mrgriscom** [comment]
Both seem like good ideas. Pixel skip seems best handled in OPC.java right before the rgb values are queued up and sent out.

**Comment by mrgriscom** [comment]
Supported in OPC; still need to support in the fadecandy json config.

**Comment by mrgriscom** [comment]
not sure if this code made it into the 2017 refactor. this didn't seem like a failure mode we experienced in practice.

**Comment by shen-tian** [comment]
No. Think physical patches are probably better.
